
language: r
os: linux
dist: xenial

cache:
  - packages
  - ccache

warnings_are_errors: FALSE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

# currently there is a bug in rstantools 2.1.0 (tbb header missing)
before_install:
  - sudo apt-get install -y libv8-dev
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_version("rstantools", version = "2.0.0", repos = "http://cran.us.r-project.org")'
  - mkdir -p ~/.R
  - echo "CXX14FLAGS=-O3 -march=native -mtune=native -fPIC" >> ~/.R/Makevars
  - echo "CXX14=g++" >> ~/.R/Makevars

script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check moultmcmc*tar.gz

after_script:
  - tar -ztvf moultmcmc_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
- cat moultmcmc.Rcheck/00*
