// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4uz12_linpred_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4uz1_linpred_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4uz2_linpred_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4uz3_linpred_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4uz3_recap_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4uz4_linpred_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4uz5_linpred_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4uz5_recap_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4uz12_linpred_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz12_linpred_mod, 0},
    {"_rcpp_module_boot_stan_fit4uz1_linpred_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz1_linpred_mod, 0},
    {"_rcpp_module_boot_stan_fit4uz2_linpred_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz2_linpred_mod, 0},
    {"_rcpp_module_boot_stan_fit4uz3_linpred_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz3_linpred_mod, 0},
    {"_rcpp_module_boot_stan_fit4uz3_recap_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz3_recap_mod, 0},
    {"_rcpp_module_boot_stan_fit4uz4_linpred_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz4_linpred_mod, 0},
    {"_rcpp_module_boot_stan_fit4uz5_linpred_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz5_linpred_mod, 0},
    {"_rcpp_module_boot_stan_fit4uz5_recap_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4uz5_recap_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_moultmcmc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
