# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("uz12_linpred", "uz1_linpred", "uz2_linpred", "uz2_recap", "uz3_linpred", "uz3_recap", "uz4_linpred", "uz5_linpred", "uz5_recap", "uz5_recap_annual_raneff")

# load each stan module
Rcpp::loadModule("stan_fit4uz12_linpred_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz1_linpred_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz2_linpred_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz2_recap_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz3_linpred_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz3_recap_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz4_linpred_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz5_linpred_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz5_recap_mod", what = TRUE)
Rcpp::loadModule("stan_fit4uz5_recap_annual_raneff_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
